CREATE TABLE IF NOT EXISTS bom (
    bom_id SERIAL PRIMARY KEY,
    name TEXT,
    module_name TEXT,
    repo TEXT,
    bpc TEXT,
    summary JSONB,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_bom_module_name ON bom(module_name);

CREATE TABLE IF NOT EXISTS activity (
    activity_id SERIAL PRIMARY KEY,
    email TEXT,
    path TEXT,
    activity_time TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- definition contains the content defined in source code.
CREATE TABLE IF NOT EXISTS definition (
    definition_id SERIAL PRIMARY KEY,
    symbol_digest BYTEA,
    content JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_definition_digest_unique ON definition(symbol_digest);

-- metadata contains the content generated by catalog.
CREATE TABLE IF NOT EXISTS metadata (
    metadata_id SERIAL PRIMARY KEY,
    definition_id INT REFERENCES definition(definition_id),
    content JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_metadata_definition_unique ON metadata(definition_id);

CREATE TABLE IF NOT EXISTS index (
    index_id SERIAL PRIMARY KEY,
    bom_id INT REFERENCES bom(bom_id),
    content JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_bom_index ON index(bom_id);

CREATE TABLE IF NOT EXISTS root (
    root_id SERIAL PRIMARY KEY,
    bom_id INT REFERENCES bom(bom_id),
    root_digest BYTEA,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS root_index ON root(bom_id);

CREATE TABLE IF NOT EXISTS scene (
    scene_id SERIAL PRIMARY KEY,
    definition_id INT REFERENCES definition(definition_id),
    object_digest BYTEA,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS scene_index ON scene(definition_id);
